apiVersion: 1

datasources:
  - name: PostgreSQL
    type: postgres
    access: proxy
    url: postgres:5432
    database: metrics_db
    user: admin
    secureJsonData:
      password: admin123
    jsonData:
      sslmode: "disable"  # Change to "require" if using SSL
      maxOpenConns: 10
      maxIdleConns: 10
      connMaxLifetime: 14400
    isDefault: true

