{
 "title": "ODC_Task_2",
 "time": { "from": "now-5m", "to": "now" },
 "refresh": "auto",
 "panels": [
  {
   "title": "App01 CPU Usage (%)",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT\n  timestamp AS \"time\",\n  cpu_usage,\n  container_name\nFROM\n  metrics\nWHERE\n  container_name = 'app01'\n  AND $__timeFilter(timestamp);"
    }
   ]
  },
  {
   "title": "App02 CPU Usage (%)",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "  SELECT\n  timestamp AS \"time\",\n  cpu_usage,\n  container_name\nFROM\n  metrics\nWHERE\n  container_name = 'app02'\n  AND $__timeFilter(timestamp);"
    }
   ]
  },
  {
   "title": "App01 RAM Usage (%)",
   "type": "bargauge",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT\n  timestamp AS \"time\",\n  ram_usage,\n  container_name\nFROM\n  metrics\nWHERE\n  container_name = 'app01'\n  AND $__timeFilter(timestamp);"
    }
   ]
  },
  {
   "title": "App02 RAM Usage (%)",
   "type": "bargauge",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT\n  timestamp AS \"time\",\n  ram_usage,\n  container_name\nFROM\n  metrics\nWHERE\n  container_name = 'app02'\n  AND $__timeFilter(timestamp);"
    }
   ]
  },
  {
   "title": "App01 Disk Usage (%)",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 14 },
   "targets": [
    {
     "rawSql": "SELECT\n  timestamp AS \"time\",\n  disk_usage,\n  container_name\nFROM\n  metrics\nWHERE\n  container_name = 'app01'\n  AND $__timeFilter(timestamp);"
    }
   ]
  },
  {
   "title": "App02 Disk Usage (%)",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 14 },
   "targets": [
    {
     "rawSql": "SELECT\n  timestamp AS \"time\",\n  disk_usage,\n  container_name\nFROM\n  metrics\nWHERE\n  container_name = 'app02'\n  AND $__timeFilter(timestamp);"
    }
   ]
  }
 ]
}